# Generated by Django 5.0.1 on 2024-01-26 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('summary', models.TextField(max_length=40000, null=True)),
                ('engine_size', models.IntegerField(null=True)),
                ('bhp_count', models.IntegerField(null=True)),
                ('mileage', models.IntegerField()),
                ('fuel', models.CharField(choices=[('benzyna', 'Benzyna'), ('benzyna+cng', 'Benzyna+CNG'), ('benzyna+lpg', 'Benzyna+LPG'), ('diesel', 'Diesel'), ('elektryczny', 'Elektryczny'), ('etanol', 'Etanol'), ('hybryda', 'Hybryda'), ('wodór', 'Wodór')])),
                ('gearbox', models.CharField(choices=[('automatyczna', 'Automatyczna'), ('manualna', 'Manualna')])),
                ('year', models.IntegerField()),
                ('price', models.IntegerField()),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cars.brand')),
            ],
        ),
    ]
