# Generated by Django 5.0.1 on 2024-01-27 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_car_fuel_alter_car_gearbox'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='lemmatized_summary',
            field=models.TextField(max_length=40000, null=True),
        ),
    ]
