# Generated by Django 5.0.1 on 2024-01-27 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_lemmatized_summary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='car',
            old_name='lemmatized_summary',
            new_name='tk_lemmatized',
        ),
    ]
